wavefrontHQ/docs

js/customscripts.js

Updated search API token with role-based user.

update algolia search API key

---

pages/doc/proxies_installing.md

Included Windows/Added Windows commands to proxy installation doc.
cc: @rkempf42

Added windows to proxy install doc

---

Gemfile
Gemfile.lock

I've never managed Gemfile before so I'd like @jbau to review this one before merging it.

Upgrade nokogiri to 1.8.2

---

pages/doc/integrations_aws_metrics.md

Add "CloudTrail Region" field description and changed word "connect" with "SET UP".

Add "CloudTrail Region" field description

---

pages/doc/ts_aliasMetric.md
pages/doc/ts_aliasSource.md
pages/doc/ts_taggify.md

- fixed inconsistencies between functions
- added "static value" syntax to each function
- cleaned up taggify (newPointTagKey)

cleaned up metadata functions

---

pages/doc/ts_substring.md

row tag missing opening bracket

formatting

---

README.md
pages/doc/wavefront_introduction.md

- Update a command in the README.md file.
- Minor fixes to the introduction page.

Minor fixes

---

pages/doc/query_language_reference.md
pages/doc/ts_limit.md

Update the following:
- The limit() description in the query reference page
- the limit time series and trace description in the specific limits function page.
- Format the note.

Shavi bug fix

---

pages/doc/trace_data_sampling.md
pages/doc/tracing_basics.md
pages/doc/tracing_instrumenting_frameworks.md
pages/doc/tracing_integrations.md

Includes Sues's 40-DT content.

Shavi 40 dt

---

pages/doc/trace_data_sampling.md
pages/doc/tracing_basics.md
pages/doc/tracing_instrumenting_frameworks.md
pages/doc/tracing_integrations.md

Revert "Shavi 40 dt"

---

pages/doc/proxies_preprocessor_rules.md

- Minor update (added a space).
- Removed a parameter from a sample.

Minor updates to the proxy-processor-rule samples.

---

pages/doc/2019_38.x_release_notes.md
pages/doc/trace_data_sampling.md
pages/doc/tracing_basics.md
pages/doc/tracing_instrumenting_frameworks.md
pages/doc/tracing_integrations.md

- Add intelligent sampling content done by Sue to 38.x
- Removed a few extra spaces.
- fixed a minor typo.

Add intelligent sampling content done by Sue to 38.x

---

pages/doc/trace_data_details.md
pages/doc/trace_data_sampling.md
pages/doc/traces_function.md

Updated content based on the feedback.

Update content around span tag length

---

pages/doc/2019_46.x_release_notes.md
pages/doc/tracing_instrumenting_frameworks.md

Update the content as per the feedback.

Minor updates

---

pages/doc/query_language_reference.md

histo takes a tsExpression (time series) as an argument.

Fixed typo on histo

---

pages/doc/ui_charts_faq.md

fix comments

---

pages/doc/tracing_instrumenting_frameworks.md

Fix capitalization in headings.

Fix capitalization in headings

---

pages/doc/wavefront_sdks.md

Add the Go metrics SDK to the list - Table and add the logo to the specific section.

Add the Go metrics SDK to the list

---

pages/doc/events.md

Fix a broken table because of the note format.

Sd bug fix

---

pages/doc/hs_function.md

Fix spacing issue

---

pages/doc/trace_data_query.md
pages/doc/tracing_ui_overview.md

update as per the feedback

---

pages/doc/wavefront_spring_boot.md
pages/doc/wavefront_spring_boot_faq.md
pages/doc/wavefront_spring_boot_tutorial.md

- Add videos as per the feedback given by Renate
- Fix a broken link

Add videos

---

pages/doc/trace_data_details.md

Fix configuration for OpenTracing SDKs for custom span-level tags.

Fix code for custom span-level tags

---

pages/doc/tracing_instrumenting_frameworks.md
pages/doc/wavefront_sdks.md

Add content on custom proxy port

Add content on custom proxy port

---

pages/doc/external_links_managing.md

Add a link from the external links docs to the integration logs doc, and fix a few minor issues.

Add a note to external links doc

---

pages/doc/tracing_basics.md
pages/doc/tracing_ui_overview.md

Add details on the upcoming compatibility matrix.

SDK compatibility matrix

---

pages/doc/wavefront_limits.md

Update to histogram length limit to 256

Update to histogram length limit to 256

---

pages/doc/wavefront_spring_boot.md
pages/doc/wavefront_spring_boot_tutorial.md

Update the Wavefront for Spring Boot version from 2.0.0-RC1 to 2.0.0

Update the Wavefront for Spring Boot version from 2.0.0-RC1 to 2.0.0

---

pages/doc/tracing_ui_overview.md

Update the Java OT SDK version to 2.1.1.

Update the Java OT SDK version

---

pages/doc/tracing_best_practices.md
pages/doc/tracing_instrumenting_frameworks.md
pages/doc/tracing_ui_overview.md

Fix broken links in the tracing pages.

Fix broken links

---

pages/doc/alert_target_customizing.md

Add Info on How to Access Specific Point Tag Value

---

_data/sidebars/doc_sidebar.yml
pages/doc/tracing_best_practices.md
pages/doc/tracing_customize_spans_and_alerts.md
pages/doc/tracing_faq.md
pages/doc/tracing_ui_overview.md
pages/doc/wavefront_spring_boot.md
pages/doc/wavefront_spring_boot_faq.md
pages/doc/wavefront_spring_boot_tutorial.md

- Add a new tracing FAQ page
- Add the app map video
- Update spring version

Add tracing FAQ and app map video

---

pages/doc/2020_38.x_release_notes.md
pages/doc/tracing_ui_overview.md

- Add the app map video to the release page.
- Add anchors to the tracing UI page - will be used by the help panel.
- Minor formatting changes on the tracing UI page.

Minor tracing doc changes

---

pages/doc/trace_data_query.md
pages/doc/tracing_faq.md

Add FAQ on the trace retention period

Add FAQ on trace retention period

---

pages/doc/auth_ss_sso.md
pages/doc/authentication.md
pages/doc/tracing_java_tutroial.md
pages/doc/wavefront_security.md
pages/doc/wavefront_spring_boot_tutorial.md

- Review changes for security and authorization pages, 
- change tracing tutorial page name, 
- and add tutorials tag for the tracing tutorial and SpringBoot tutorial.

Update docs (Review, tracing tutorial name change )

---

pages/doc/wavefront_spring_boot.md

Update Wavefront for Spring Boot release version

---

pages/doc/integrations.md

$subject from the integration overview page.

Remove redundant content

---

pages/doc/trace_data_query.md
pages/doc/tracing_view_offline_traces.md

- Fix formatting issue on the offline traces page
- Fix minor typo on query trace data page.

Fix formatting issues

---

pages/doc/wavefront_obsolescence_policy.md

Adding information about internal metrics to Delta Counter migration doc

Internal metrics info for Delta Counters

---

pages/doc/integrations_new_changed.md

Updated the Integrations release notes for the release in March.

Integrations rel notes for the March release.

---

pages/doc/integrations_aws_ecs.md

Update to AWS ECS doc to reflect the custom port setup changes.

Documenting new fargate collector for AWS

---

pages/doc/integrations_new_changed.md

Update to the integrations release notes for the release of catchpoint.

updated the integrations rel notes

---

pages/doc/hello_wavefront_aws_tutorial.md
pages/doc/ts_default.md
pages/doc/videos_data.md

Including the video on sending Windows host metrics to Wavefront into the Hello WF tutorial and the list of WF videos. Minor fix to the default function as well.

Including the Windows video

---

pages/doc/ts_default.md

Making some fixes to the default function doc, and improving the text about the .orElse operator.

Fixes to the default function doc

---

pages/doc/ts_default.md

Replaced an expression in the default function doc.

Incorporated more feedback

---

pages/doc/dashboards_variables.md
pages/doc/ui_dashboards.md
pages/doc/ui_sharing.md

Included links to the permissions topic.

Minor fixes .

---

pages/doc/tracing_instrumenting_frameworks.md

Add a link to the KB article OpenTracing or OpenTelemetry.

Add a link to the KB article OpenTracing or OpenTelemetry.

---

pages/doc/authorization.md
pages/doc/charts_customizing.md
pages/doc/charts_events_displaying.md
pages/doc/integrations_aws_metrics.md
pages/doc/integrations_aws_overview.md
pages/doc/integrations_pcf_alerts.md
pages/doc/integrations_vsphere.md
pages/doc/metrics_security.md
pages/doc/permissions.md
pages/doc/tags_overview.md
pages/doc/ui_chart_reference.md
pages/doc/webhooks_alert_notification.md

Documented what Comma Delimited check box selection does and made some other fixes - split checkbox to two words, made some code fixes to the pcf alerts as well.

Fix typos and an issue

---

pages/doc/2021-14.x_release_notes.md

Added images to the release notes

Adding images to the RNs.

---

pages/doc/metrics_security.md

Incorporated one suggestion to the new example on restricting role-based access.

One suggestion to the new example.

---

pages/doc/videos_query_language.md
pages/doc/wavefront_prometheus.md

Updated the PromQL video and included it in the docs. will release it with 19.x

Included the promql video

---

pages/doc/2021-19.x_release_notes.md

Update to the grouped rel notes for the 15-19 releases

Update to the rel notes

---

pages/doc/wavefront_release_notes.md

Improving the wording of the RNs

Some improvements to the RNs

---

pages/doc/query_language_reference.md
pages/doc/wavefront_release_notes.md

Included the new functions in the QL reference page and addressed doc feedback.

Incorporated feedback

---

pages/doc/integrations_new_changed.md

Added the June section to the Integrations release notes.

June rel notes

---

pages/doc/integrations_new_changed.md

Minor update

---

pages/doc/integrations.md

Feedback from Conor

---

pages/doc/integrations.md

Added information that reinstalling the predefined alerts reverts the changes.

Minor edit to the Alerts tab description

---

pages/doc/wavefront_release_notes.md

Added the bullet for accessibility improvements.

Minor update to the RNs.

---

_data/sidebars/doc_sidebar.yml
pages/doc/integrations_new_changed.md
pages/doc/integrations_new_changed_2018.md
pages/doc/integrations_new_changed_2020.md
pages/doc/wavefront_release_notes.md

Changed the title of the integrations release notes.

Change the title of the Int. release notes

---

pages/doc/integrations_new_changed_2018.md

+ Renaming the Int. Release Notes page

tiny update

---

integrations/adfs.md
integrations/azure_ad.md
integrations/google.md
integrations/okta.md
integrations/onelogin.md
integrations/pingone.md
integrations/workspace-one.md
pages/doc/access.md
pages/doc/authorization.md
pages/doc/user_accounts.md
pages/doc/users_groups.md
pages/doc/wavefront_acessibility.md
pages/doc/wavefront_release_notes.md

Updated release notes and replaced user name with username throughout the docs.

Minor improvements to the docs

---

pages/doc/dashboards_variables.md
pages/doc/ingestion_policies.md
pages/doc/tracing_service_dashboard.md
pages/doc/tutorial_getting_started.md
pages/doc/ui_dashboards.md
pages/doc/wavefront_spring_boot_tutorial.md

Replacing pulldown/pull-down/dropdown with drop-down menu throughout the docs (except in old RNs).

Minor change

---

pages/doc/integrations_log_data.md
pages/doc/wavefront_release_notes.md

Made a minor change to the RNs and updated the Combined Apache Logs link in Log Data Metrics Integration to point to the latest Apache docs version (http://httpd.apache.org/docs/2.4/logs.html#combined).

Minor changes

---

integrations/dataplatforms.md
integrations/vmware_cloud_pks.md
pages/doc/accounts.md
pages/doc/authorization.md
pages/doc/monitoring_wavefront_proxy.md
pages/doc/users_roles.md
pages/doc/wavefront_monitoring.md
pages/doc/wavefront_monitoring_spy.md
pages/doc/wavefront_security.md

Some typos

---

pages/doc/wavefront_release_notes.md

Removed the note as it won't be needed now.

Removed the note as it won't be needed

---

pages/doc/anomaly_detection.md

Removed the note saying we'll enable the feature for all customers in the upcoming releases.

Removing the note 

---

pages/doc/integrations.md

Made minor improvements to the Integrations overview

Minor improvements

---

pages/doc/integrations_new_changed.md

Integrations release notes

---

pages/doc/videos_query_language.md

Made a fix to the descriptions of the last 2 videos.

A fix to the video descriptions

---

_data/sidebars/doc_sidebar.yml
pages/doc/monitoring_overview.md

Removed Finding Ingestion and Query Problems from the TOC and fixed some typos in the same topic.

Removed a topic from the TOC

---

pages/doc/videos_dashboards_charts.md

Made a fix to the table (added a closing row tag)

A fix to the table

---

css/wavefront-doc-style.css
pages/doc/6x_release_notes.md

Sowmya helped fix the search bar cutting off issue when the page is smaller.

Merge Sowmya's fix

---

pages/doc/wavefront_api.md

Add info about required permissions for Access API

---

pages/doc/integrations_new_changed.md

Updated the integrations release notes with more release information.

Updates for today's integrations release

---

pages/doc/integrations.md

Included a note that after installing the alerts, customers have to set alert targets.

Including a note about the alerts.

---

pages/doc/integrations.md
pages/doc/integrations_pcf_alerts.md
pages/doc/query_language_getting_started.md
pages/doc/videos_query_language.md
pages/doc/wavefront_prometheus.md

Changed name from Pivotal Cloud Foundry to Tanzu Application Service.

Renamed PCF to TAS

---

js/customscripts.js

Adds a resizing event listener to handle browser changes without removing search component

Search fix for resizing browser window

---

pages/doc/ui_sharing.md
pages/doc/wavefront_release_notes.md

Documented a UI change

---

pages/doc/wavefront_release_notes.md

Highlighted a sentence in yellow.

Change to the RNs

---

pages/doc/proxies_configuring.md

Removed some strange characters from the Configuring Proxies doc.

Removed some strange characters 

---

pages/doc/integrations_ibmcloud_thirdparty.md

Minor fixes to the IBM integration doc.

Minor doc fixes

---

pages/doc/integrations_new_changed.md

Updated the Integration rel notes.

New bullet for the TAS Gorouter changes

---

pages/doc/integrations_new_changed.md

Fixed a typo in the name of the TAS integration

Fix a typo

---

pages/doc/integrations_new_changed.md

Gemfire name fix

---

pages/doc/integrations_new_changed.md

Added a bullet to the integrations release notes

---

pages/doc/integrations_new_changed.md

Int rel notes

---

_data/sidebars/doc_sidebar.yml
pages/doc/integrations_new_changed.md
pages/doc/integrations_vrops.md
pages/doc/wavefront_release_notes.md

Merging the vROps docs with the 114 branch in which this feature is supposed to go out

Merge vROps docs

---

pages/doc/integrations_new_changed.md

Updated the integration release notes with the latest January info.

Integrations rel notes

---

pages/doc/integrations_new_changed.md

Publish the integration release notes & snowflake.

Publishing the Int. rel notes

---

pages/doc/direct_ingestion.md
pages/doc/integrations_aws_metrics.md
pages/doc/integrations_aws_overview-API.md
pages/doc/integrations_aws_overview.md
pages/doc/permissions_overview.md
pages/doc/tracing_basics.md
pages/doc/ui_chart_reference.md
pages/doc/ui_charts_faq.md
pages/doc/ui_examine_data.md
pages/doc/ui_sharing.md
pages/doc/wavefront_monitoring_spy.md

Also,  included the note.html where we talk about permissions.

Some minor changes to the AWS API setup doc.

---

pages/doc/integrations_new_changed.md

Rel Notes and some other integrations-related docs.

Integrations docs

---

pages/doc/examine-usage-ingestion.md
pages/doc/ingestion_policies.md
pages/doc/monitoring_overview.md

Fixed some "broken" links and added information about the slow query dashboard.

Fixed some links

---

pages/doc/authorization_faq.md

about what the super admin user can do

Added a bullet

---

pages/doc/wavefront_administer.md

Found another broken link, fixing it

---

pages/doc/integrations_aws_metrics.md

Moving out a section that seems no longer valid.

Moving out a section.

---

pages/doc/wavefront_release_notes.md

Updated the announcement for SAs removal from Everyone group to add a link to the RNs from last year.

Updated the announcement for SAs to add a link

---

index_header.md
pages/doc/wavefront_spring_boot.md

Update the spring version and a minor update to the welcome page

Updated the Spring version

---

pages/doc/wavefront_release_notes.md

Improve rel notes

---

pages/doc/alerts_v2_faq.md

Add a note on the new alert GUI FAQ on the terraform compatibility.

Add note a note  

---

_data/sidebars/doc_sidebar.yml
pages/doc/wavefront_api.md
pages/doc/wavefront_command-line_interfaces.md
pages/doc/wavefront_interfaces.md
pages/doc/wavefront_sdks.md

Changes related to the update of product name

name changes

---

pages/doc/integrations_aws_overview.md
pages/doc/integrations_new_changed.md
pages/doc/wavefront_security.md

And made minor fixes to two links

Commenting out the Int rel notes

---

pages/doc/integrations_grafana.md

the url is not valid when there is a www

remove www from the url

---

pages/doc/2020_30.x_release_notes.md
pages/doc/2021-14.x_release_notes.md
pages/doc/access.md
pages/doc/accounts-service.md
pages/doc/accounts.md
pages/doc/alerts.md
pages/doc/authentication.md
pages/doc/authorization_faq.md
pages/doc/documentation_getting_started.md
pages/doc/integrations.md
pages/doc/integrations_aws_overview-API.md
pages/doc/integrations_aws_overview.md
pages/doc/integrations_new_changed.md
pages/doc/metrics_security.md
pages/doc/monitoring_overview.md
pages/doc/proxies_manual_install.md
pages/doc/query_language_getting_started.md
pages/doc/trace_data_query.md
pages/doc/trace_sampling_policies.md
pages/doc/tracing_integrations.md
pages/doc/tracing_operation_dashboard.md
pages/doc/tracing_service_dashboard.md
pages/doc/tracing_traces_browser.md
pages/doc/tracing_ui_overview.md
pages/doc/ui_charts.md
pages/doc/ui_dashboards.md
pages/doc/ui_examine_data.md
pages/doc/users_account_managing.md
pages/doc/wavefront_acessibility.md
pages/doc/wavefront_support_feedback.md

Replaced taskbar with toolbar throughout the docs

Replace taskbar with toolbar

---

_data/sidebars/doc_sidebar.yml
pages/doc/integrations_aws_metrics.md

Include information on AWS Usage metrics

---

pages/doc/ingestion_policies.md
pages/doc/proxies_troubleshooting.md

Cherry picked some doc improvements (a note in the IP doc and some formatting fixes to the proxy TS doc) from another branch, so that I can publish these to the web.

Some minor doc improvements

---

pages/doc/integrations.md

Commented out a section in the integrations doc.

Remove a section from the doc

---

pages/doc/ts_rawcount.md

Should be rawcount vs ts_rawcount

Fixed a typo in rawcount name

---

pages/doc/tracing_best_practices.md
pages/doc/tracing_customize_spans_and_alerts.md
pages/doc/wavefront_release_notes.md

Update that the custom span tag limit is now 50 (was 25)

custom span tag limit to 50

---

pages/doc/proxies_configuring.md

- Pulled content from the otel repo
- update the proxy config

OpenTelemetry Metrics-Proxy

---

pages/doc/integrations_aws_metrics.md

Added some info about CloudWatch point tags.

added info about point tags.

---

pages/doc/tas_to_troubleshoot.md

@rkempf42 -- what do you think about making a few additions to the TAS integration troubleshooting guide? This PR isn't very polished, but I would like to give folks a little bit more detail about how to see any errors that are happening on their telegraf or wavefront proxy VMs.
I also was skeptical about saying 'wait a few hours' when it comes to the tile installation in Ops Manager. If the tile install has completed, there should be metrics flowing already.
It might make sense to have a dedicated section for how to view the telegraf agent logs and the wavefront proxy logs, then link to that section from the **potential solutions**
I'm happy to make any of those changes - just wanted to get early feedback from you based on your experience.

additional TAS content

---

pages/doc/logging_proxy_configurations.md

update proxy version 11.2 to 11.3

Update proxy version for otel and logs

---

pages/doc/integrations_tas_howto.md

Uncomment Saved Searches info
Remove 1 item from TAS-TO-Howto (no longer in GUI)

Misc. minor bug fixes

---

pages/doc/wavefront_spring_boot_faq.md

Added the content to the Spring Boot FAQs and commented it out as we discussed.

add content on freemium account deleted error

---

pages/doc/2022-06.x_release_notes.md
pages/doc/alerts_faq.md
pages/doc/query_language_align_function.md
pages/doc/tas_to_troubleshoot.md
pages/doc/wavefront_usage_info.md

Top-level is fine, but needed a few section link fixes

A few section link fixes.

---

pages/doc/integrations_new_changed.md

Integration release notes for August release.

Integration release notes

---

pages/doc/2022-20.x_release_notes.md
pages/doc/logging_faq.md

- Added an FAQ to lgs on how to know if the proxy is sending data
- Pull the Otel readme structure change

Logs FAQ and OTel changes

---

pages/doc/2022-20.x_release_notes.md

The Otel content seems to have gone missing. Adding it back again.

Add back otel content

---

pages/doc/videos.md
pages/doc/videos_kubernetes.md
pages/doc/wavefront_kubernetes.md

Updated several doc pages to include links to the new video.

New video for K8s Operator

---

.github/workflows/DependabotReview.yaml
.github/workflows/ScanCode.yaml

Adds CodeQL code scanning as well as a dependency review to PR's.

WFESO-4850 Add code scanning to repo

---

pages/doc/logging_faq.md
pages/doc/logging_log_browser.md
pages/doc/logging_overview.md
pages/doc/logging_proxy_configurations.md
pages/doc/logging_send_logs.md
pages/doc/wavefront_limits.md

Update the logs docs:
- Update the docs as per Bohyun and Amit's feedback
- Update the proxy config with sean's help

Update logs docs

---

pages/doc/proxies_troubleshooting.md

Commenting out instructions that are currently not working.

Update to Proxies Troubleshooting

---

pages/doc/integrations_aws_overview.md

Peer review feedback and improvements to AWS doc after discussion with dev and IX.

Mstaneva doc fixes

---

pages/doc/cardinality.md
pages/doc/ts_default.md
pages/doc/ts_last.md
pages/doc/ts_next.md

some WQL functions and cardinality depend on the metrics obsolescence period

---

pages/doc/tas_to_troubleshoot.md

This is in service of this story from the tas2to team's backlog: https://www.pivotaltracker.com/story/show/184226731

Add draft writeup copied from story

---

pages/doc/tas_to_troubleshoot.md

Minor fixes - commands for deleting the app and the route were listed twice.

Fix to the doc

---

integrations/amazon_eks.md
integrations/ceph.md
integrations/dataplatforms.md
integrations/envoy.md
integrations/filebeat.md
integrations/kubernetes.md
integrations/log.md
integrations/openshift.md
integrations/rancher.md
integrations/redis.md
integrations/tmc.md
integrations/vsphere_tanzu.md
pages/doc/dashboards_variables.md
pages/doc/integrations_aws_metrics.md
pages/doc/integrations_new_changed.md
pages/doc/wavefront_release_notes.md
pages/doc/wavefront_spring_boot_faq.md

Added a bullet about the custom namespaces to the:
- Service RNs
- Integrations RNs

RNs and a feature

---

pages/doc/integrations_tas_howto.md

These are not ready to be merged yet, as we have not released the feature. We are hoping to get feedback on this early, so it can be merged in quickly once we release the next version of our tile.

Tas v4 service broker docs 182873676

---

pages/doc/integrations_tas_howto.md

TAS to TO had a release on Friday night. I have to push the doc changes live

Minor edits

---

pages/doc/2023-06.x_release_notes.md
pages/doc/wavefront_release_notes.md
pages/doc/webhooks_alert_notification.md

Please take a look and merge, if you approve, because you're the owner of the release

Alert targets + RNs

---

pages/doc/tracing_traces_browser.md
pages/doc/tracing_ui_overview.md

Juhi requested that we remove the saved search feature from docs for the time being.

Comment out the saved search content

---

pages/doc/integrations_new_changed.md

Mstaneva integrations

---

pages/doc/integrations_aws_metrics.md
pages/doc/integrations_new_changed.md
pages/doc/logging_overview.md

Please review - I added a new section in the AWS doc page so that I can point to it from the rel notes. And I also removed a note  from the logs docs (we had two almost identical notes one under another)

AWS Logs Beta setup docs

---

pages/doc/integrations_new_changed_2022.md
pages/doc/integrations_pks.md
pages/doc/integrations_pks_archived.md
pages/doc/kubernetes_troubleshoot.md
pages/doc/kubernetes_troubleshooting.md
pages/doc/videos_kubernetes.md
pages/doc/wavefront_kubernetes.md
pages/doc/wavefront_kubernetes_faq.md
pages/doc/wavefront_obsolescence_policy.md

Kubernetes Metrics Collector. Updated this throughout

Collector for Kubernetes name will be 

---

pages/doc/direct_ingestion.md

Updated the doc page per request from the support team.

Updating direct data ingestion doc page

---

pages/doc/alerts_best_practices.md
pages/doc/metrics_managing.md
pages/doc/missing_data_troubleshooting.md
pages/doc/sources_managing.md

Some improvements to the text about the obsolescence period. Please review

Some improvements

---

pages/doc/query_language_performance.md
pages/doc/query_language_reference.md
pages/doc/sources_managing.md
pages/doc/tags_overview.md

Some minor linguistic fixes. I also enhanced the information about wildcards. Please review.

Info about wildcards

---

pages/doc/opentelemetry_java_tutorial.md

Tested the tutorial and updates the steps to help the user.

[OpenTelemetry] Updates to the java auto instrumentation tutorial 

---

pages/doc/query_language_series_joining.md
pages/doc/tracing_basics.md
pages/doc/wavefront_data_format.md
pages/doc/wavefront_data_ingestion.md
pages/doc/wavefront_introduction.md
pages/doc/wavefront_monitoring_spy.md
pages/doc/wavefront_prometheus.md
pages/doc/wavefront_sdks.md
pages/doc/wavefront_searching.md
pages/labels/label_videos.md

With info when the video was created and if the video has screencaptures - the UI version.

Updated more doc pages with embedded videos

---

pages/doc/logging_faq.md
pages/doc/logging_overview.md
pages/doc/logging_send_logs.md

- Update FAQ to remove the limits
- Remove the log limits from the docs

Remove log limits

---

pages/doc/start_trial.md

try to kick off a build as well

Include the note as it's okay to be published now. 

---

pages/doc/wavefront_spring_boot3.md

Update the docs to set the freemium account setting to false when you already have an instance.

Update SpringBoot 3 docs

---

_config.yml
pages/doc/2021-24.x_release_notes.md
pages/doc/alerts_manage.md
pages/doc/charts_events_displaying.md
pages/doc/derived_metrics.md
pages/doc/hello_wavefront_aws_tutorial.md
pages/doc/integrations_aws_metrics.md
pages/doc/metrics_managing.md
pages/doc/proxies_installing.md
pages/doc/proxies_kube_container.md
pages/doc/query_language_aggregate_functions.md
pages/doc/tracing_instrumenting_frameworks.md
pages/doc/tracing_integrations.md
pages/doc/ui_charts.md
pages/doc/ui_dashboards.md
pages/doc/wavefront_support_feedback.md

Updated all KB links to point to the new portal, deleted the references to the OpenTelemetry KB because it no longer exists.

Updated the links to the support portal

---

_includes/topnav.html

update the content so when you click the logo on the header it does not navigate to docs.wavefront but rather the section you are in

Update the logo link

---

pages/doc/wavefront_spring_boot3.md

Added info on how to connect to VMware Cloud Service account.

CSP updates for Wavefront for Spring Boot
