wavefrontHQ/docs

pages/doc/2017_32.x_release_notes.md

Fixed extra space to be consistent with doc and pagerduty's website.

fixed Pager Duty to PagerDuty (no space)

---

pages/doc/direct_ingestion.md

Use Wavefront domain instead of localhost in the examples.

Update direct ingestion documentation

---

pages/doc/proxies_histograms.md

For 22.x, we no longer have the 'histogram.' prefix

no prefix for 22.x

---

pages/doc/proxies_configuring.md

The pushlistenerport accepts HTTP data, in the format listed in the change.  Both TCP and HTTP data are accepted.

Add HTTP support documentation for Pushlistener

---

pages/doc/proxies_configuring.md

Fixed proxy config options
`ephemeral` is now in the proper place alphabetically

proxy config: ephemeral is in wrong order

---

pages/doc/proxies_preprocessor_rules.md

- Changes tag to key in the spanAdd and spanDrop samples.
- Marked the firstMatchOnly parameter as optional.
- Formatted the samples so everything is in the same format. (tabs and alignment)

Fix a bug in a sample and format the samples.

---

pages/doc/wavefront_sdks.md

Fixed the image for C++ that was broken on the SDK page.

Fix broken image

---

pages/doc/proxies_configuring.md
pages/doc/proxies_versions.md

Updated the following as per the feedback from Vassily.
`buffer: `this setting is available since the beginning of time, not 3.20
`ephemeral`: defaults to true starting with 6.0
`idFile`: defaults to ~/.dshell/id (has always been the case). ignored when ephemeral=true
`pushBlockedSamples`: defaults to 5 since 5.0
`pushLogLevel`: deprecated since 6.0, level of logging is controlled through log4j2 config.
`histogramHttpBufferSize`: Maximum allowed request size (in bytes) for incoming HTTP requests on histogram ports (Default: 16MB)
`traceListenerHttpBufferSize`: Maximum allowed request size (in bytes) for incoming HTTP requests with tracing data (Default: 16MB)
`rawLogsHttpBufferSize`: Maximum allowed request size (in bytes) for incoming HTTP requests with raw logs (Default: 16MB) …

Add proxy configurations

---

css/wavefront-doc-style.css
pages/doc/proxies_versions.md

- If we use text in code format and a link in code format in the same sentence, the link overlaps the text. This fixes the issue (-7 px > 1 px)
- Minor update to proxy 6.1 release notes.

Minor CSS improvement

---

pages/doc/permissions_overview.md

- Remove the last point of the page, which was redundant.
- Format the notes.

Remove redundant content from permission_overview.

---

pages/doc/wavefront_spring_boot.md

Add info on new spring boot configurations
* added a point on `wavefront.freemium-account=true`
* info on how to stop integration tests from sending data to Wavefront:   `management.metrics.export.wavefront.enabled=false`

Add info on new spring boot configurations

---

pages/doc/metric_types.md

- Fix a typo - was supposed to be a link
- Fix typo in delta counter section
- Removed a link that no longer existed (Traces example)'
- Added a link to traces and span explanation

Fix broken links, typo, and removed link that is no longer in docs

---

pages/doc/proxies_preprocessor_rules.md

Realized that the example provided in the Proxy GitHub is actually incorrect (just filed a PR to correct that). The way "global" rules work is that they apply to all explicitly specified ports in the preprocessor rule file. Additionally, the global rules must be at the end of the file (since it looks for all previously specified ports in the file and so, if the global rule was at the beginning, there would be no other rules above/previous to it). Hope that makes sense

Update info for global rules

---

pages/doc/tracing_operation_dashboard.md

- added option 3: drill down through the trace browser
- removed 2 points that don't work to drill down to the traces browser

Update Operation Dashboard content

---

pages/doc/wavefront_obsolescence_policy.md

clarifying migration to delta counters for the situation where the rate function is used with the timeWindow parameter

clarify migration for rate functions

---

pages/doc/tracing_instrumenting_frameworks.md

Removed the example for the sender SDK because it is no longer correct after discussing with Han

Removed the example for the sender SDK 

---

pages/doc/trace_data_query.md
pages/doc/tracing_faq.md

Remove the $subject as spans are only stored for 7 days.

Remove the line contact support to extend the retention period.

---

integrations/amazon_eks.md
integrations/kubernetes.md
integrations/openshift.md
integrations/rancher.md
integrations/tmc.md
integrations/vsphere_tanzu.md
pages/doc/integrations_new_changed.md
pages/doc/kubernetes_troubleshoot.md
pages/doc/wavefront_kubernetes.md
pages/doc/wavefront_kubernetes_faq.md

Co-authored-by: John Cornish <jcornish@vmware.com>
On searching for "master" branch name usage with wavefront-collector-for-kubernetes repo across [wavefrontHQ/docs](https://github.com/wavefrontHQ/docs), we found more changes necessary than the files mentioned in [this slack thread](https://vmware.slack.com/archives/C0JFMBSSF/p1652087716332819?thread_ts=1651784507.272959&cid=C0JFMBSSF). So we went ahead and changed them all.

Changing default branch name to main for wavefront-collector-for-kubernetes

---

pages/doc/proxies_preprocessor_rules.md

This PR removes a line from the `metricsFilter` example that currently implies that this filter supports glob patterns.
This PR also attempts to show how a regex example should handle escaping a literal `.` character.

clarify preprocess metricsFilter documentation

---

README.md

This isn't necessary, but I found that adding this flag sped up the server by quite a bit when I updated individual files. It seemed to regenerate every single file even if only one was changed initially, and this flag seems to cause it to only regenerate changed files.

Add the --incremental flag to the jekyll command in the readme

---

pages/doc/wavefront_internal_metrics.md
pages/doc/webhooks_alert_notification.md

Removing the note, the team implemented some changes and the notes are no longer needed

Removed the note about alerting on ~alert

---

pages/doc/tas_to_troubleshoot.md
pages/doc/wavefront_api.md

TAS and a link in the Troubleshooting missing data

KB content

---

pages/doc/wavefront_spring_boot3.md

I updated the section with a new tab for existing projects that are configured with an Operations for Applications account.
They no longer need to use the wavefront for sprint boot starter dependency. The micrometer has it by default.

Add info on customers using micrometer-wavefront-tracing
